Repository amethyst/amethyst, pull requests merged in 2018-09, with the labels that each got.

#926 Fix the application_root_dir function
  amethyst_locale/src/lib.rs
  amethyst_utils/src/app_root_dir.rs
  src/app.rs
Labels: pri: blocker, project: workflow, status: ready, type: bug

#920 Added ArcThreadPool, camera ortho, removal and timed destroy
  amethyst_assets/src/prefab/system.rs
  amethyst_core/src/axis.rs
  amethyst_core/src/lib.rs
  amethyst_utils/Cargo.toml
  amethyst_utils/src/lib.rs
  amethyst_utils/src/ortho_camera.rs
  amethyst_utils/src/removal.rs
  amethyst_utils/src/scene.rs
  amethyst_utils/src/time_destroy.rs
  book/src/game-data.md
  docs/CHANGELOG.md
  examples/custom_game_data/game_data.rs
  src/game_data.rs
Labels: status: ready, type: feature

#933 fix: Joint entities could only be part of a single skin.
  amethyst_animation/src/skinning/resources.rs
  amethyst_animation/src/skinning/systems.rs
  amethyst_gltf/src/format/skin.rs
  amethyst_renderer/src/pipe/effect/mod.rs
  docs/CHANGELOG.md
  examples/assets/prefab/puffy_scene.ron
  src/logger.rs
Labels: project: animation, project: gltf, status: ready, type: bug

#952 New specs
  amethyst_core/Cargo.toml
  amethyst_renderer/src/pass/flat/separate.rs
  amethyst_renderer/src/pass/pbm/separate.rs
  amethyst_renderer/src/pass/shaded/separate.rs
  amethyst_ui/src/event.rs
  amethyst_ui/src/layout.rs
Labels: pri: low, project: rendering, project: ui, status: ready, type: improvement

#962 Update an example from the System book chapter
  amethyst_renderer/src/pass/debug_lines/interleaved.rs
  book/src/concepts/state.md
  book/src/concepts/system.md
Labels: project: docs, status: ready, type: improvement

#963 Make Travis test the book
  .travis.yml
  book/src/concepts/system.md
  book/src/prefab.md
  travis.sh
Labels: project: docs, status: ready, type: improvement

#973 Add missing cmake dependency to instructions
  README.md
Labels: project: docs, status: ready, type: improvement
