Repository amethyst/amethyst, pull requests merged in 2018-08, with the labels that each got.

#848 Put in a better example for Component in the book
  book/src/concepts/component.md
Labels: project: docs, status: review comments, type: improvement

#850 Fix compile errors in pong-tutorial-01 for amethyst 0.8.0
  book/src/pong-tutorial/pong-tutorial-01.md
Labels: project: docs, status: ready, type: bug

#881 Various docs improvements.
  book/src/concepts/dispatcher.md
  book/src/concepts/event-channel.md
  book/src/concepts/world.md
  book/src/game-data.md
  book/src/pong-tutorial/pong-tutorial-01.md
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: pri: normal, project: docs, status: ready, type: improvement

#891 Updated dependencies
  README.md
  book/src/getting-started.md
Labels: pri: low, project: meta, status: ready, type: improvement

#915 fix: Until the asset caching situation is cleared up, remove ids from…
  amethyst_gltf/src/format/material.rs
  docs/CHANGELOG.md
Labels: project: gltf, status: ready, type: bug

#916 feat: Add ability to control logging config via environment
  src/logger.rs
Labels: project: main crate, status: ready, type: improvement

#925 fix: Disable backface culling for the sprite pass
  amethyst_renderer/src/pass/sprite/interleaved.rs
  amethyst_renderer/src/pipe/effect/mod.rs
Labels: project: rendering, status: ready, type: bug
