Repository amethyst/amethyst, pull requests merged in 2018-03, with the labels that each got.

#604 Converting f32 arrays without alphas to TextureData
  amethyst_renderer/src/formats/texture.rs
Labels: project: rendering, status: ready, type: improvement

#612 Remove unwrap in amethyst::animation
  amethyst_animation/src/systems/control.rs
Labels: project: animation, status: ready, type: bug

#614 Add Discord badge
  README.md
Labels: project: meta, status: ready, type: improvement
