Repository amethyst/amethyst, pull requests merged in 2018-12, with the labels that each got.

#1195 Improve documentation for fly control functionality
  amethyst_controls/src/bundles.rs
  amethyst_controls/src/systems.rs
Labels: project: docs, status: ready, type: improvement

#1188 Adds CameraOrthoPrefab
  amethyst_utils/src/ortho_camera.rs
  docs/CHANGELOG.md
Labels: project: assets, status: ready, type: improvement

#1206 Add warning about using EventChannel with pausable systems
  amethyst_core/src/system_ext.rs
Labels: project: docs, status: ready, type: improvement

#1226 Migrate book to 2018 edition idioms
  book/src/concepts/state.md
  book/src/concepts/system.md
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-03.md
  book/src/pong-tutorial/pong-tutorial-04.md
  book/src/pong-tutorial/pong-tutorial-05.md
  book/src/sprites/display_the_texture.md
  book/src/sprites/load_the_texture.md
  book/src/sprites/orthographic_camera.md
  book/src/sprites/sprite_render_component.md
  book/src/testing.md
  src/app.rs
  tests/amethyst_test/src/lib.rs
Labels: project: docs, type: improvement

#1237 Derive `Copy`, `PartialEq`, `Eq`, `Serialize`, `Deserialize` on `Flipped` component.
  amethyst_renderer/src/sprite.rs
  docs/CHANGELOG.md
Labels: project: rendering, status: ready

#1232 Add some docs for actions.
  amethyst_input/src/bindings.rs
Labels: project: docs, status: review comments, type: improvement

#1242 Maintenance/update vergen
  Cargo.toml
  build.rs
Labels: project: main crate, status: ready

#1255 Push renderer to 0.10.1
  amethyst_renderer/Cargo.toml
Labels: project: rendering, status: ready, type: bug

#1273 Correct documented name for CameraOrthoSystem
  amethyst_utils/src/ortho_camera.rs
Labels: project: docs, status: ready, status: waiting on merge, type: bug

#1276 Fix a 404 in the book
  book/src/sprites.md
Labels: project: docs, status: ready, status: waiting on merge

#1288 Create back-reference from Pausable
  amethyst_core/src/system_ext.rs
Labels: project: docs, status: ready, type: improvement

#1297 Minor fix to resolve compile error.
  book/src/pong-tutorial/pong-tutorial-03.md
Labels: project: docs, status: waiting on merge, type: bug

#1281 add AutoFov for automatic resizing of camera
  Cargo.toml
  amethyst_utils/src/auto_fov.rs
  amethyst_utils/src/lib.rs
  docs/CHANGELOG.md
  examples/assets/prefab/auto_fov.ron
  examples/assets/ui/fov.ron
  examples/auto_fov/main.rs
  examples/auto_fov/resources/display.ron
Labels: project: core, status: ready, type: improvement
