Repository amethyst/amethyst, pull requests merged in 2018-06, with the labels that each got.

#757 Formatting with rustfmt 0.4.2-stable
  amethyst_animation/src/skinning/systems.rs
  amethyst_animation/src/transform.rs
  amethyst_animation/src/util.rs
  amethyst_assets/examples/hl.rs
  amethyst_assets/src/progress.rs
  amethyst_assets/src/storage.rs
  amethyst_audio/src/components/audio_emitter.rs
  amethyst_audio/src/output.rs
  amethyst_audio/src/sink.rs
  amethyst_audio/src/systems/audio.rs
  amethyst_controls/src/lib.rs
  amethyst_controls/src/systems.rs
  amethyst_gltf/src/format/importer.rs
  amethyst_gltf/src/format/mod.rs
  amethyst_input/src/bundle.rs
  amethyst_renderer/src/color.rs
  amethyst_renderer/src/formats/mesh.rs
  amethyst_renderer/src/formats/texture.rs
  amethyst_renderer/src/mesh.rs
  amethyst_renderer/src/pass/flat/interleaved.rs
  amethyst_renderer/src/pass/flat/separate.rs
  amethyst_renderer/src/pass/shaded_util.rs
  amethyst_renderer/src/pass/util.rs
  amethyst_renderer/src/pipe/effect/mod.rs
  amethyst_renderer/src/system.rs
  amethyst_renderer/src/tex.rs
  amethyst_renderer/src/vertex.rs
  amethyst_renderer/src/visibility.rs
  amethyst_ui/src/button.rs
  amethyst_ui/src/pass.rs
  amethyst_ui/src/text.rs
  examples/appendix_a/main.rs
  examples/appendix_a/systems/bounce.rs
  examples/appendix_a/systems/move_balls.rs
  examples/appendix_a/systems/paddle.rs
  examples/appendix_a/systems/winner.rs
  examples/arc_ball_camera/main.rs
  examples/custom_game_data/main.rs
  examples/fly_camera/main.rs
  examples/pong/main.rs
  examples/pong/pong.rs
  examples/pong/systems/bounce.rs
  examples/pong/systems/move_balls.rs
  examples/pong/systems/paddle.rs
  examples/pong/systems/winner.rs
  examples/pong_tutorial_01/main.rs
  examples/pong_tutorial_02/main.rs
  examples/pong_tutorial_03/main.rs
  examples/renderable/main.rs
  examples/sprites/main.rs
  examples/ui/main.rs
  rustfmt.toml
  src/error.rs
  src/game_data.rs
Labels: project: meta, status: ready, type: maintenance

#756 feat: Add alpha cutoff support to the PBR shader
  amethyst_renderer/src/mtl/mod.rs
  amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
  amethyst_renderer/src/system.rs
Labels: project: rendering, status: ready, type: improvement

#759 feat: Add utilities for dealing with common inputs
  amethyst_controls/Cargo.toml
  amethyst_controls/src/lib.rs
  amethyst_input/src/lib.rs
  amethyst_input/src/util.rs
  book/src/game_data.md
  book/src/pong_tutorial/pong_tutorial_01.md
  examples/animation/main.rs
  examples/appendix_a/pong.rs
  examples/arc_ball_camera/main.rs
  examples/asset_loading/main.rs
  examples/custom_game_data/input.rs
  examples/custom_game_data/main.rs
  examples/fly_camera/main.rs
  examples/gltf/main.rs
  examples/material/main.rs
  examples/pong/pong.rs
  examples/pong_tutorial_01/main.rs
  examples/pong_tutorial_02/pong.rs
  examples/pong_tutorial_03/pong.rs
  examples/renderable/main.rs
  examples/separate_sphere/main.rs
  examples/sphere/main.rs
  examples/sphere_multisample/main.rs
  examples/sprites/main.rs
  examples/ui/main.rs
  examples/window/main.rs
Labels: project: input, status: ready, type: improvement

#766 Fix color format
  amethyst_renderer/src/vertex.rs
Labels: project: rendering, status: ready, type: bug

#768 Fix UI images
  amethyst_ui/src/pass.rs
Labels: project: ui, status: ready, type: bug

#767 Fix resize on OSX
  amethyst_renderer/src/renderer.rs
Labels: project: rendering, status: ready, type: bug

#772 Use fresnel function instead of duplicating inline in PBM shader
  amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
Labels: project: rendering, status: ready, type: improvement

#770 feat: Add bundle for arc ball camera
  amethyst_controls/src/bundles.rs
  amethyst_controls/src/lib.rs
  amethyst_controls/src/systems.rs
  amethyst_input/src/lib.rs
  examples/animation/main.rs
  examples/arc_ball_camera/main.rs
  examples/asset_loading/main.rs
  examples/custom_game_data/main.rs
  examples/fly_camera/main.rs
  examples/gltf/main.rs
  examples/material/main.rs
  examples/pong/pong.rs
  examples/pong_tutorial_01/main.rs
  examples/pong_tutorial_02/pong.rs
  examples/pong_tutorial_03/pong.rs
  examples/renderable/main.rs
  examples/separate_sphere/main.rs
  examples/sphere/main.rs
  examples/sphere_multisample/main.rs
  examples/sprites/main.rs
  examples/ui/main.rs
  examples/window/main.rs
Labels: project: controls, status: ready, type: improvement

#773 Make more info available for asset error handling
  amethyst_assets/examples/hl.rs
  amethyst_assets/src/error.rs
  amethyst_assets/src/progress.rs
  amethyst_assets/src/storage.rs
  amethyst_ui/src/pass.rs
Labels: project: assets, status: ready, type: improvement

#779 Fix some minor correctness issues for UI
  amethyst_ui/src/text.rs
  amethyst_ui/src/transform.rs
Labels: project: ui, status: ready, type: bug

#716 feat: Add prefab loading
  Cargo.toml
  amethyst_animation/src/lib.rs
  amethyst_animation/src/prefab.rs
  amethyst_animation/src/skinning/resources.rs
  amethyst_assets/Cargo.toml
  amethyst_assets/src/lib.rs
  amethyst_assets/src/prefab/impls.rs
  amethyst_assets/src/prefab/mod.rs
  amethyst_assets/src/prefab/system.rs
  amethyst_audio/Cargo.toml
  amethyst_audio/src/components/mod.rs
  amethyst_audio/src/lib.rs
  amethyst_audio/src/source.rs
  amethyst_controls/Cargo.toml
  amethyst_controls/src/components.rs
  amethyst_controls/src/lib.rs
  amethyst_renderer/src/cam.rs
  amethyst_renderer/src/formats/mesh.rs
  amethyst_renderer/src/formats/mod.rs
  amethyst_renderer/src/formats/mtl.rs
  amethyst_renderer/src/formats/texture.rs
  amethyst_renderer/src/lib.rs
  amethyst_renderer/src/light.rs
  amethyst_renderer/src/resources.rs
  amethyst_renderer/src/shape.rs
  amethyst_renderer/src/skinning.rs
  amethyst_ui/src/layout.rs
  amethyst_ui/src/lib.rs
  amethyst_ui/src/prefab.rs
  amethyst_ui/src/text.rs
  amethyst_ui/src/transform.rs
  amethyst_utils/src/tag.rs
  book/src/prefab.md
  examples/README.md
  examples/animation/main.rs
  examples/assets/prefab/example.ron
  examples/prefab/main.rs
  examples/prefab/resources/display_config.ron
  examples/renderable/main.rs
  examples/sphere/main.rs
  examples/sphere_multisample/main.rs
  examples/sprites/main.rs
  examples/ui/main.rs
  src/app.rs
Labels: project: assets, status: ready, type: improvement

#786 feat: Specialised UI prefab format
  amethyst_ui/src/lib.rs
  amethyst_ui/src/prefab.rs
  book/src/prefab.md
  examples/assets/ui/renderable.ron
  examples/renderable/main.rs
Labels: project: assets, project: ui, status: ready, type: improvement

#791 feat: Add basic scene utility prefab
  amethyst_controls/src/lib.rs
  amethyst_renderer/src/formats/mesh.rs
  amethyst_renderer/src/vertex.rs
  amethyst_utils/Cargo.toml
  amethyst_utils/src/lib.rs
  amethyst_utils/src/scene.rs
  examples/assets/prefab/example.ron
  examples/prefab/main.rs
  examples/prefab/resources/display_config.ron
Labels: project: assets, status: ready, type: improvement

#804 Add beginner-friendly sprite rendering utilities
  amethyst_renderer/src/error.rs
  amethyst_renderer/src/lib.rs
  amethyst_renderer/src/sprite.rs
  amethyst_renderer/src/tex.rs
  examples/assets/img/pong_spritesheet.png
  examples/pong/main.rs
  examples/pong/pong.rs
  examples/pong/systems/bounce.rs
  examples/pong/systems/paddle.rs
Labels: project: animation, project: rendering, status: ready, type: feature
