Repository amethyst/amethyst, pull requests merged in 2018-11, with the labels that each got.

#1088 refactor: Relax Copy constraint on interpolation primitives
  amethyst_animation/Cargo.toml
  amethyst_animation/src/resources.rs
  amethyst_animation/src/systems/sampling.rs
Labels: project: animation, status: ready, type: improvement

#1100 Add documentation to prefab_data_derive
  amethyst_derive/src/lib.rs
  book/src/prefab.md
Labels: project: assets, project: docs, status: merging

#1111 Fix redundant_closure lint
  amethyst_derive/src/event_reader.rs
Labels: status: waiting on merge

#1090 feat: Add a asset loading helper to abstract away the asset loading internals
  amethyst_assets/src/helper.rs
  amethyst_assets/src/lib.rs
  docs/CHANGELOG.md
  examples/material/main.rs
Labels: project: assets, status: ready, type: improvement

#1116 refactor: Add internal material cache to gltf loading
  amethyst_gltf/src/format/mod.rs
  amethyst_gltf/src/lib.rs
  amethyst_renderer/src/formats/mtl.rs
Labels: project: gltf, status: ready, type: improvement

#1124 Fix offsets field in define_the_sprite_sheet.md
  book/src/sprites/define_the_sprite_sheet.md
Labels: project: docs, status: discussing

#1117 refactor: Use texture handle directly in spritesheets
  amethyst_renderer/src/lib.rs
  amethyst_renderer/src/mtl.rs
  amethyst_renderer/src/pass/sprite/interleaved.rs
  amethyst_renderer/src/sprite.rs
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-04.md
  book/src/sprites/define_the_sprite_sheet.md
  book/src/sprites/load_the_texture.md
  book/src/sprites/sprite_render_component.md
  docs/CHANGELOG.md
  examples/pong/pong.rs
  examples/pong_tutorial_02/pong.rs
  examples/pong_tutorial_03/pong.rs
  examples/sprites_ordered/main.rs
  examples/sprites_ordered/sprite_sheet_loader.rs
  tests/amethyst_test/src/fixture/sprite_render_animation_fixture.rs
Labels: project: rendering, status: ready, type: improvement

#1099 Create sprite_camera_follow example
  Cargo.toml
  docs/CHANGELOG.md
  examples/sprite_camera_follow/main.rs
  examples/sprite_camera_follow/resources/Background.png
  examples/sprite_camera_follow/resources/Background.ron
  examples/sprite_camera_follow/resources/Circle_Spritesheet.png
  examples/sprite_camera_follow/resources/Circle_Spritesheet.ron
  examples/sprite_camera_follow/resources/display_config.ron
  examples/sprite_camera_follow/resources/input.ron
Labels: project: docs, project: rendering, status: ready, type: improvement

#1133 use reexported types instead of log::LevelFilter
  src/logger.rs
Labels: status: waiting on merge

#1132 move spritesheet definition to next chapter
  book/src/pong-tutorial/pong-tutorial-01.md
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: project: docs

#1142 Use new_observer_frame in Transform::look_at
  amethyst_core/src/transform/components/local_transform.rs
  docs/CHANGELOG.md
Labels: project: core, status: ready

#1150 Fix regression in GLTF loading after #1075 (fixes #1145)
  amethyst_gltf/src/format/mod.rs
Labels: project: gltf, status: merging, type: bug

#1156 Remove unused fern dependency in amethyst_network
  amethyst_network/Cargo.toml
  amethyst_network/src/lib.rs
Labels: project: networking, status: waiting on merge, type: improvement

#1153 Implement a way of rendering images without spritesheets (Fixes #1086)
  Cargo.toml
  amethyst_renderer/src/lib.rs
  amethyst_renderer/src/pass/flat2d/interleaved.rs
  amethyst_renderer/src/pass/flat2d/mod.rs
  amethyst_renderer/src/pass/mod.rs
  amethyst_renderer/src/pass/sprite/interleaved.rs
  amethyst_renderer/src/sprite.rs
  book/src/SUMMARY.md
  book/src/pong-tutorial/pong-tutorial-01.md
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-04.md
  book/src/pong-tutorial/pong-tutorial-05.md
  book/src/sprites/display_the_texture.md
  book/src/sprites/set_up_the_render_pass.md
  book/src/sprites/sprite_render_component.md
  docs/AUTHORS.md
  docs/CHANGELOG.md
  examples/pong/main.rs
  examples/pong/pong.rs
  examples/pong_tutorial_01/main.rs
  examples/pong_tutorial_02/main.rs
  examples/pong_tutorial_02/pong.rs
  examples/pong_tutorial_03/main.rs
  examples/pong_tutorial_03/pong.rs
  examples/pong_tutorial_04/main.rs
  examples/pong_tutorial_04/pong.rs
  examples/pong_tutorial_05/main.rs
  examples/pong_tutorial_05/pong.rs
  examples/simple_image/main.rs
  examples/simple_image/resources/display_config.ron
  examples/simple_image/resources/logo.png
  examples/sprite_camera_follow/main.rs
  examples/sprites_ordered/main.rs
  tests/amethyst_test/src/amethyst_application.rs
Labels: pri: normal, project: rendering, status: merging, type: feature, type: improvement

#1161 Move windows to allowed failures.
  .travis.yml
Labels: project: workflow, status: ready

#1144 Bugfix: Dynamically generated texture buffers have the wrong size
  amethyst_renderer/src/error.rs
  amethyst_renderer/src/formats/texture.rs
  amethyst_renderer/src/tex.rs
  docs/CHANGELOG.md
Labels: project: rendering, status: discussing, type: bug

#1155 Added nalgebra migration notes to book.
  book/src/SUMMARY.md
  book/src/appendices/b_migration_notes.md
  book/src/appendices/b_migration_notes/cgmath_to_nalgebra.md
Labels: project: docs, status: ready

#1163 Reintroduce the update world warning for States
  book/src/concepts/state.md
Labels: project: docs, status: waiting on merge, type: improvement

#1164 Deny unknown fields for BasicScenePrefab
  amethyst_utils/src/scene.rs
  docs/CHANGELOG.md
Labels: project: assets, status: ready, status: waiting on merge, type: improvement

#1052 Add doctests to Transform, reorder set_rotation_euler arguments.
  amethyst_core/src/transform/components/local_transform.rs
  docs/CHANGELOG.md
Labels: project: core, project: docs, status: ready, type: improvement

#1171 Small reformat and edits of the Pong tutorial
  book/src/SUMMARY.md
  book/src/pong-tutorial/pong-tutorial-01.md
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-03.md
  book/src/pong-tutorial/pong-tutorial-04.md
  book/src/pong-tutorial/pong-tutorial-05.md
Labels: project: docs, status: waiting on merge

#1169 Clean unused glyph brushes
  amethyst_ui/src/pass.rs
Labels: project: ui, status: ready

#1191 Fix link to docs label in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: project: docs, status: ready, type: bug

#1192 Fix CameraOrtho when coordinates are upside-down
  amethyst_utils/src/ortho_camera.rs
Labels: project: rendering, status: merging, type: bug
