Repository amethyst/amethyst, pull requests merged in 2018-05, with the labels that each got.

#684 Use contains() where appropriate
  amethyst_animation/src/resources.rs
  amethyst_animation/src/systems/control.rs
  amethyst_animation/src/util.rs
  amethyst_renderer/src/visibility.rs
  amethyst_ui/src/layout.rs
  amethyst_ui/src/pass.rs
  amethyst_ui/src/text.rs
Labels: pri: low, project: rendering, project: ui, status: ready, type: improvement

#688 fix: Temporary patch for coreaudio-sys (mac)
  Cargo.toml
Labels: diff: easy, pri: important, project: audio, status: ready

#695 Repatch coreaudio-sys due to branch deletion
  Cargo.toml
Labels: project: audio, status: ready, type: bug

#694 Fix fly_camera demos window focus
  amethyst_controls/Cargo.toml
  amethyst_controls/src/bundles.rs
  amethyst_controls/src/lib.rs
  amethyst_controls/src/resources.rs
  amethyst_controls/src/systems.rs
Labels: status: ready, type: improvement

#697 Re-use vec allocation for event compression
  amethyst_renderer/src/system.rs
Labels: pri: low, project: rendering, status: ready, type: improvement

#702 Use derivative default better
  amethyst_input/src/input_handler.rs
Labels: pri: low, project: input, status: ready

#709 fix: Update shred/specs/etc after SystemData refactor
  amethyst_animation/src/resources.rs
  amethyst_animation/src/systems/control.rs
  amethyst_core/Cargo.toml
  amethyst_core/src/transform/systems.rs
  amethyst_gltf/src/systems.rs
  amethyst_ui/Cargo.toml
  amethyst_ui/src/button.rs
  amethyst_ui/src/layout.rs
  examples/animation/main.rs
  examples/appendix_a/systems/bounce.rs
  examples/renderable/main.rs
  src/app.rs
Labels: pri: normal, project: core, status: ready, type: maintenance

#728 Remove appveyor cache dependencies
  .appveyor.yml
Labels: project: workflow, status: ready, type: task

#723 Add new things to Changelog
  docs/CHANGELOG.md
Labels: project: meta, status: ready, type: task

#718 Fixes Transform's to_matrix method
  amethyst_core/src/transform/components/local_transform.rs
Labels: project: core, status: waiting on merge, type: bug

#727 Editorial pass
  docs/CONTRIBUTING.md
  docs/FEATURES.md
Labels: project: docs, status: ready, type: improvement

#706 Add issue templates
  docs/ISSUE_TEMPLATE/bug_report.md
Labels: project: meta, status: ready

#738 Make a few additions to the Introduction chapter
  book/src/intro.md
Labels: project: docs, status: ready, status: waiting on merge, type: improvement

#741 Specify which `cargo fmt`
  docs/CONTRIBUTING.md
Labels: project: docs, status: ready, status: waiting on merge, type: improvement

#744 Remove unnecessary log warning
  amethyst_core/src/transform/systems.rs
Labels: pri: normal, project: core, status: ready, type: improvement

#745 Add bullet point to features (2D & 3D)
  docs/FEATURES.md
Labels: project: docs, status: ready, type: improvement

#749 fix: Log an error if a pass tries to render a mesh with incompatible vertex buffers
  amethyst_renderer/src/pass/util.rs
Labels: project: rendering, status: discussing, type: improvement

#755 Improve examples on OSX
  amethyst_controls/src/bundles.rs
  amethyst_controls/src/lib.rs
  amethyst_controls/src/systems.rs
  amethyst_renderer/src/resources.rs
  amethyst_renderer/src/system.rs
  examples/arc_ball_camera/main.rs
Labels: project: controls, status: ready, type: improvement
