Repository amethyst/amethyst, pull requests merged in 2018-10, with the labels that each got.

#987 Bumped dependency versions.
  Cargo.toml
  amethyst_network/Cargo.toml
  amethyst_network/src/lib.rs
  amethyst_renderer/Cargo.toml
  amethyst_ui/Cargo.toml
Labels: project: meta, status: ready, status: waiting on merge, type: improvement

#998 Fix for dragging between monitors with different DPIs
  amethyst_renderer/src/renderer.rs
Labels: project: rendering, status: ready, status: waiting on merge, type: bug

#1010 Nix gitter refs
  amethyst_renderer/README.md
  book/src/getting-started.md
  book/src/intro.md
  docs/CONTRIBUTING.md
Labels: project: meta, status: ready, type: improvement

#1008 fix: Rename functions on PrefabData to be easier to understand
  amethyst_animation/src/prefab.rs
  amethyst_animation/src/skinning/resources.rs
  amethyst_assets/src/prefab/impls.rs
  amethyst_assets/src/prefab/mod.rs
  amethyst_assets/src/prefab/system.rs
  amethyst_audio/src/components/mod.rs
  amethyst_audio/src/source.rs
  amethyst_controls/src/components.rs
  amethyst_gltf/src/lib.rs
  amethyst_renderer/src/cam.rs
  amethyst_renderer/src/formats/mesh.rs
  amethyst_renderer/src/formats/mod.rs
  amethyst_renderer/src/formats/mtl.rs
  amethyst_renderer/src/formats/texture.rs
  amethyst_renderer/src/light.rs
  amethyst_renderer/src/resources.rs
  amethyst_renderer/src/shape.rs
  amethyst_renderer/src/skinning.rs
  amethyst_ui/src/prefab.rs
  amethyst_utils/src/removal.rs
  amethyst_utils/src/scene.rs
  amethyst_utils/src/tag.rs
  book/src/prefab.md
  docs/CHANGELOG.md
  examples/gltf/main.rs
Labels: project: assets, status: ready, type: improvement

#1013 Fixes to the component chapter
  book/src/concepts/component.md
Labels: project: docs, status: ready, type: improvement

#1025 Fix denial of warnings
  src/app.rs
  travis.sh
Labels: project: meta, status: ready, status: waiting on merge, type: improvement

#1012 Only specify GL profile on macos
  amethyst_renderer/src/renderer.rs
  docs/CHANGELOG.md
Labels: project: rendering, status: ready, type: improvement

#1024 [Fix] Ui examples prefab was broken
  amethyst_assets/src/prefab/mod.rs
  amethyst_renderer/src/formats/texture.rs
  docs/CHANGELOG.md
Labels: project: docs, status: waiting on merge, type: bug

#1026 Fix MacOS 10.14 nothing rendering until resize
  amethyst_renderer/src/renderer.rs
  docs/CHANGELOG.md
Labels: pri: critical, project: rendering, status: ready, status: waiting on merge, type: bug

#1027 Also work with Debian!
  README.md
Labels: project: docs, status: waiting on merge, type: improvement

#1033 Derive Serialize for NetConnection
  amethyst_network/src/connection.rs
Labels: project: networking, status: waiting on merge, type: improvement

#1034 Update & simplify contributing document
  docs/CONTRIBUTING.md
Labels: project: docs, project: meta, status: ready, status: waiting on merge, type: improvement

#1042 Fix UI caching
  amethyst_ui/src/pass.rs
Labels: project: ui, status: ready, status: waiting on merge, type: bug

#1067 Add Config::load_bytes for user to include configs in binary
  amethyst_config/src/lib.rs
  docs/CHANGELOG.md
Labels: project: config, status: merging, type: improvement

#1070 Replace `GlobalTransform` with `Transform` in all examples
  amethyst_renderer/src/pass/sprite/interleaved.rs
  amethyst_renderer/src/visibility.rs
  book/src/prefab.md
  examples/appendix_a/pong.rs
  examples/arc_ball_camera/main.rs
  examples/asset_loading/main.rs
  examples/custom_game_data/graphic.rs
  examples/debug_lines/main.rs
  examples/fly_camera/main.rs
  examples/gltf/main.rs
  examples/material/main.rs
  examples/sprites_ordered/main.rs
  tests/amethyst_test/src/amethyst_application.rs
Labels: project: docs, status: merging, type: improvement

#1071 [Fix] Reformat and fix Concept/Resource example code
  book/src/concepts/resource.md
Labels: project: docs, status: review comments, type: improvement

#1077 Small fix to the README
  README.md
Labels: project: docs, status: ready, type: improvement

#1074 added directional light support to PBM shader
  amethyst_renderer/src/pass/shaders/fragment/pbm.glsl
Labels: project: rendering, status: waiting on merge, type: feature

#1087 Provide associated constants for Rgba colors
  amethyst_renderer/src/color.rs
Labels: project: rendering, status: merging, type: improvement
