Repository amethyst/amethyst, pull requests merged in 2019-10, with the labels that each got.

#1949 Update pong-tutorial amethyst version to 0.13.
  book/src/pong-tutorial/pong-tutorial-01.md
Labels: status: waiting for merge, team: documentation

#1953 Fix changelog merge mistake
  docs/CHANGELOG.md
Labels: status: done, team: documentation

#1955 Maintenance/update dependencies
  amethyst_animation/Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_core/Cargo.toml
  amethyst_gltf/Cargo.toml
  amethyst_input/Cargo.toml
  amethyst_network/Cargo.toml
  amethyst_tiles/Cargo.toml
  amethyst_ui/Cargo.toml
Labels: status: waiting for merge, team: engine

#1965 Publish v0.13.1
  Cargo.toml
  amethyst_animation/Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_core/Cargo.toml
  amethyst_derive/Cargo.toml
  amethyst_gltf/Cargo.toml
  amethyst_input/Cargo.toml
  amethyst_locale/Cargo.toml
  amethyst_network/Cargo.toml
  amethyst_tiles/Cargo.toml
  amethyst_ui/Cargo.toml
  docs/CHANGELOG.md
Labels: pri: critical, status: done, team: engine

#1969 Include note about `with_system_desc` in specs migration notes
  book/src/appendices/b_migration_notes/specs_migration.md
Labels: status: done, team: documentation

#1979 Fix typo in pong-tutorial-06
  book/src/pong-tutorial/pong-tutorial-06.md
Labels: status: done, team: documentation

#1972 Add mention of how read_resource has moved
  book/src/appendices/b_migration_notes/specs_migration.md
Labels: status: done, team: documentation

#1978 Fix #1947: Add an entry for tiles to examples readme
  docs/CHANGELOG.md
  examples/README.md
  examples/assets/img/tiles.png
Labels: status: done, team: documentation

#1900 Refer to `amethyst_rendy` via `amethyst::renderer`
  examples/rendy/prefab_data.rs
Labels: status: needs author changes, team: rendering

#1981 Fix Pong Tutorial background music
  book/src/pong-tutorial/pong-tutorial-06.md
Labels: status: done, team: documentation

#1999 Fix pong tutorial background music
  book/src/pong-tutorial/pong-tutorial-06.md
Labels: status: done, team: documentation

#1998 Update `from_config_path` call.
  examples/rendy/main.rs
Labels: status: done, team: documentation

#2003 s/Point3/Vector3/ in tiles Map documentation.
  amethyst_tiles/src/map.rs
Labels: status: done, team: documentation

#1908 rendy -> 0.4.1
  Cargo.toml
  amethyst_rendy/Cargo.toml
  amethyst_rendy/src/formats/texture.rs
  amethyst_rendy/src/pass/base_3d.rs
  amethyst_rendy/src/pass/debug_lines.rs
  amethyst_rendy/src/pass/flat2d.rs
  amethyst_rendy/src/pass/mod.rs
  amethyst_rendy/src/pass/skybox.rs
  amethyst_rendy/src/pipeline.rs
  amethyst_tiles/src/pass.rs
  amethyst_ui/src/pass.rs
  examples/custom_render_pass/custom_pass.rs
Labels: status: done, team: rendering

#2012 Fix Arch Linux installation line in documentation
  README.md
Labels: status: waiting for merge, team: documentation

#2013 Dependency instructions for Nix/NixOS
  README.md
Labels: status: waiting for merge, team: documentation
