Repository amethyst/amethyst, pull requests merged in 2019-09, with the labels that each got.

#1935 Add animation support for UiTransform
  amethyst_animation/Cargo.toml
  amethyst_animation/src/lib.rs
  amethyst_animation/src/ui_transform.rs
  docs/CHANGELOG.md
Labels: status: done, team: engine

#1934 Use World::get_mut with amethyst_derive
  amethyst_derive/src/system_desc.rs
Labels: status: done, team: ecs

#1942 Publish v0.13.0 & add doc page on publishing
  Cargo.toml
  amethyst_animation/Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_audio/Cargo.toml
  amethyst_config/Cargo.toml
  amethyst_controls/Cargo.toml
  amethyst_core/Cargo.toml
  amethyst_derive/Cargo.toml
  amethyst_error/Cargo.toml
  amethyst_gltf/Cargo.toml
  amethyst_input/Cargo.toml
  amethyst_locale/Cargo.toml
  amethyst_network/Cargo.toml
  amethyst_rendy/Cargo.toml
  amethyst_test/Cargo.toml
  amethyst_tiles/Cargo.toml
  amethyst_ui/Cargo.toml
  amethyst_utils/Cargo.toml
  amethyst_window/Cargo.toml
  docs/PUBLISHING.md
Labels: status: ready, team: engine

#1944 Update changelog for 0.13
  docs/CHANGELOG.md
Labels: status: ready, team: engine

#1945 Add missing re-export for HideHierarchySystemDesc
  amethyst_core/src/lib.rs
  docs/CHANGELOG.md
Labels: status: waiting for merge, team: engine
