Repository amethyst/amethyst, pull requests merged in 2019-11, with the labels that each got.

#2025 Bump nalgebra to 0.19
  amethyst_core/Cargo.toml
Labels: status: waiting for merge, team: engine

#2028 Fix regression caused by #1908
  examples/assets/prefab/renderable.ron
  examples/assets/prefab/rendy_example_scene.ron
  examples/assets/prefab/sprite_animation.ron
  examples/assets/prefab/sprite_animation_test.ron
Labels: status: done, team: rendering

#2021 fix link to specs book
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: status: waiting for merge, team: documentation

#2036 Fix examples using ron spritesheets
  examples/assets/texture/Background.ron
  examples/assets/texture/Circle_Spritesheet.ron
  examples/assets/texture/cp437_20x20.ron
  examples/assets/texture/crate_spritesheet.ron
  examples/assets/texture/pong_spritesheet.ron
  examples/tiles/main.rs
Labels: status: done, team: documentation

#2039 Fix archlinux pkg name
  README.md
Labels: status: waiting for merge, team: documentation

#2043 Bumped `smallvec` dependency to 1.0.
  amethyst_audio/Cargo.toml
Labels: status: waiting for merge, team: audio
