Repository amethyst/amethyst, pull requests merged in 2019-06, with the labels that each got.

#1660 Fix remaining code of book/controlling_system_execution
  book/src/controlling_system_execution/pausable_systems.md
  book/src/controlling_system_execution/state-specific_dispatcher.md
Labels: status: done, team: documentation

#1654 Updating pong-tutorial and pong-tutorial-01
  book/src/pong-tutorial.md
  book/src/pong-tutorial/pong-tutorial-01.md
Labels: team: documentation

#1677 Fix prefab chapters
  book/src/prefabs/how_to_define_prefabs_adapter.md
  book/src/prefabs/how_to_define_prefabs_aggregate.md
  book/src/prefabs/how_to_define_prefabs_prelude.md
  book/src/prefabs/prefabs_technical_explanation.md
Labels: status: done, team: documentation

#1694 Remove custom release profile config
  Cargo.toml
Labels: team: engine, type: maintenance

#1710 Remove outdated note about EGL from README
  README.md
Labels: status: done

#1712 Update feature gates chapter
  book/src/appendices/c_feature_gates.md
Labels: status: done, team: documentation

#1732 Fix a few nits in the input system
  amethyst_input/src/axis.rs
  amethyst_input/src/bindings.rs
  amethyst_input/src/event.rs
  amethyst_input/src/input_handler.rs
Labels: pri: low, status: done, team: engine, type: improvement

#1723 Fix doc links in amethyst_rendy, bump versions
  Cargo.toml
  amethyst_rendy/Cargo.toml
  amethyst_rendy/src/lib.rs
Labels: status: done, team: documentation

#1720 Fix stackoverflow when serializing dyn Format
  amethyst_assets/src/asset.rs
  amethyst_assets/src/dyn_format.rs
  amethyst_audio/src/formats.rs
  amethyst_locale/src/lib.rs
  amethyst_rendy/src/formats/mesh.rs
  amethyst_rendy/src/formats/texture.rs
  amethyst_ui/src/format.rs
Labels: status: done, team: assets

#1762 Associate event reader with connection in network server example
  examples/net_server/main.rs
Labels: status: done, team: network
