Repository amethyst/amethyst, pull requests merged in 2019-12, with the labels that each got.

#2001 Add errors to the types of events which can be sent on the EventChannel
  amethyst_network/src/simulation/events.rs
  amethyst_network/src/simulation/message.rs
  amethyst_network/src/simulation/transport/laminar.rs
  amethyst_network/src/simulation/transport/tcp.rs
  amethyst_network/src/simulation/transport/udp.rs
  docs/CHANGELOG.md
  examples/net_server/main.rs
Labels: status: done, team: network

#1705 Implement the mouse as input axis
  amethyst_input/src/axis.rs
  amethyst_input/src/bindings.rs
  amethyst_input/src/input_handler.rs
  amethyst_input/src/lib.rs
  amethyst_input/src/mouse.rs
Labels: status: waiting for merge, team: engine

#2078 Fix dead link in pong tutorial
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: status: waiting for merge, team: documentation

#2075 Fix camera::Perspective::new documentation degrees -> radians
  amethyst_rendy/src/camera.rs
Labels: status: done, team: documentation

#2070 Changed Panic to return an error type
  amethyst_rendy/src/camera.rs
  book/src/pong-tutorial/pong-tutorial-02.md
  build.rs
  docs/CHANGELOG.md
  src/logger.rs
Labels: status: done, team: engine

#2082 Fix custom assets book page to use `ProcessableAsset` instead of out-…
  book/src/assets/how_to_define_custom_assets.md
Labels: status: done
