Repository amethyst/amethyst, pull requests merged in 2019-02, with the labels that each got.

#1393 Add a missing dep to our debian deps list
  README.md
Labels: status: ready, team: engine, type: improvement

#1395 Make proposed changes to review process official
  docs/CONTRIBUTING.md
Labels: status: ready, team: engine, type: maintenance

#1398 Add pull request template
  .github/pull_request_template.md
Labels: status: ready, team: engine, type: maintenance

#1400 Remove unnecessary string allocs
  amethyst_derive/src/event_reader.rs
  amethyst_renderer/src/blink.rs
Labels: status: ready, team: engine, type: maintenance

#1415 Improve documentation for logger env variables
  src/logger.rs
Labels: status: done, team: engine, type: improvement

#1419 Move transparent to default
  amethyst_renderer/src/pass/flat/interleaved.rs
  amethyst_renderer/src/pass/flat/separate.rs
  amethyst_renderer/src/pass/flat2d/interleaved.rs
  amethyst_renderer/src/pass/pbm/interleaved.rs
  amethyst_renderer/src/pass/pbm/separate.rs
  amethyst_renderer/src/pass/shaded/interleaved.rs
  amethyst_renderer/src/pass/shaded/separate.rs
  amethyst_renderer/src/pass/util.rs
  docs/CHANGELOG.md
  examples/gltf/main.rs
  examples/simple_image/main.rs
  examples/sprite_camera_follow/main.rs
  examples/sprites_ordered/main.rs
  tests/amethyst_test/src/amethyst_application.rs
Labels: status: done, team: rendering

#1421 Add initial roadmap
  docs/ROADMAP.md
Labels: status: waiting for merge, team: documentation, type: maintenance

#1433 Correct path to display_config.ron
  examples/arc_ball_camera/main.rs
Labels: status: done, type: bug
