Repository amethyst/amethyst, pull requests merged in 2019-05, with the labels that each got.

#1553 Change panic to a silent failure in UI layout Hierarchy handling
  amethyst_ui/src/layout.rs
Labels: pri: low, status: done, type: bug

#1569 Fix example due to rotations deserialization changes
  examples/assets/prefab/auto_fov.ron
  examples/assets/prefab/example.ron
  examples/assets/prefab/puffy_scene.ron
  examples/assets/prefab/renderable.ron
  examples/assets/prefab/sphere.ron
  examples/assets/prefab/spotlights_scene.ron
Labels: status: done, team: engine, type: bug

#1616 Work around false positive warning
  amethyst_error/src/lib.rs
Labels: status: done, team: engine

#1640 Add code coverage
  Jenkinsfile
Labels: status: done, team: infrastructure, type: feature

#1639 [Rendy] Change camera back to global matrix
  amethyst_core/src/transform/components/transform.rs
  amethyst_rendy/Cargo.toml
  amethyst_rendy/benches/camera.rs
  amethyst_rendy/src/camera.rs
Labels: regression, team: engine, type: bug

#1648 Make window example short again
  examples/window/main.rs
Labels: team: documentation, type: improvement

#1659 Update assets chapter after rendy integration
  book/src/assets/how_to_define_custom_assets.md
  book/src/assets/how_to_use_assets.md
Labels: status: done, team: documentation
