Repository amethyst/amethyst, pull requests merged in 2019-01, with the labels that each got.

#1301 Fix documented system name
  amethyst_controls/src/bundles.rs
Labels: project: docs, status: waiting on merge, type: improvement

#1289 Parallel Packet Processing
  amethyst_network/src/bundle.rs
  amethyst_network/src/connection.rs
  amethyst_network/src/error.rs
  amethyst_network/src/lib.rs
  amethyst_network/src/net_event.rs
  amethyst_network/src/network_socket.rs
  amethyst_network/src/server/config.rs
  amethyst_network/src/server/host.rs
  amethyst_network/src/server/mod.rs
  amethyst_network/src/server/receive_handler.rs
  amethyst_network/src/server/send_handler.rs
  amethyst_network/src/server/server_socket_event.rs
  amethyst_network/src/server/udp.rs
  amethyst_network/src/test.rs
  examples/net_client/main.rs
  examples/net_server/main.rs
Labels: project: networking, status: review comments, type: improvement

#1317 Update discord links
  README.md
  amethyst_renderer/README.md
  book/src/intro.md
  book/src/pong-tutorial/contribution.md
  docs/CONTRIBUTING.md
Labels: project: meta, status: ready, type: improvement

#1307 Change the recommended donation website
  README.md
Labels: project: docs, status: ready, type: improvement

#1320 Fix #1319
  amethyst_utils/src/ortho_camera.rs
Labels: project: rendering, status: ready, type: bug

#1321 Update pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: project: docs, status: ready, type: bug

#1335 ignore send_receive_100_packets to prevent sporadic build breakage
  amethyst_network/src/test.rs
Labels: status: ready, team: network, type: maintenance

#1330 Fixed link in `README.md` to point to correct URL.
  README.md
Labels: status: ready

#1342 coding conventions for error handling
  docs/CODING_CONVENTIONS.md
Labels: status: in progress, team: documentation, type: maintenance

#1356 Remove DjSystem from AudioBundle
  amethyst_audio/src/bundle.rs
  docs/CHANGELOG.md
  examples/appendix_a/main.rs
  examples/pong/main.rs
Labels: status: ready, team: audio, type: improvement

#1327 Update cargo toml with release docs and remove appveyor badge
  Cargo.toml
  amethyst_animation/Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_audio/Cargo.toml
  amethyst_config/Cargo.toml
  amethyst_controls/Cargo.toml
  amethyst_core/Cargo.toml
  amethyst_derive/Cargo.toml
  amethyst_gltf/Cargo.toml
  amethyst_input/Cargo.toml
  amethyst_locale/Cargo.toml
  amethyst_network/Cargo.toml
  amethyst_renderer/Cargo.toml
  amethyst_ui/Cargo.toml
  amethyst_utils/Cargo.toml
  book/src/intro.md
  book/src/pong-tutorial/pong-tutorial-01.md
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-03.md
  book/src/pong-tutorial/pong-tutorial-04.md
Labels: status: ready, type: improvement

#1358 Added prefab meta-guide.
  book/src/SUMMARY.md
  book/src/prefabs/how_to_define_prefabs_adapter.md
  book/src/prefabs/how_to_define_prefabs_aggregate.md
  book/src/prefabs/how_to_define_prefabs_asset.md
  book/src/prefabs/how_to_define_prefabs_multi_handle.md
  book/src/prefabs/how_to_define_prefabs_prelude.md
  book/src/prefabs/how_to_define_prefabs_simple.md
Labels: status: done, team: assets, team: documentation

#1360 Ignore Rustfmt warning on stable for unstable configuration key.
  .concourse/tasks/linux-rustfmt.yml
  .gitlab-ci.yml
Labels: status: waiting for merge, team: infrastructure

#1362 Replace EmptyState in API doc
  src/lib.rs
Labels: status: waiting for merge, team: documentation

#1370 Docs/1114 prefab guides aggregate
  book/src/prefabs/how_to_define_prefabs_aggregate.md
  book/src/prefabs/how_to_define_prefabs_simple.md
  book/src/prefabs/prefabs_in_amethyst.md
  book/src/prefabs/prefabs_technical_explanation.md
Labels: status: done, team: assets, team: documentation

#1377 Clean up README.md, update outdated link
  README.md
Labels: status: done, team: documentation

#1383 [Fix] Ui performance on windows + nvidia gpu
  amethyst_ui/Cargo.toml
Labels: pri: critical, status: done, team: rendering, team: ui
