Repository amethyst/amethyst, pull requests merged in 2020-01, with the labels that each got.

#2084 Fix minor grammatical error in pong tutorial
  book/src/pong-tutorial/pong-tutorial-02.md
Labels: status: done, team: documentation

#2059 [BUGFIX] Fix encoders dimensional cases and optimize storage space
  amethyst_tiles/src/lib.rs
  amethyst_tiles/src/map.rs
  amethyst_tiles/src/morton/mod.rs
Labels: status: needs author changes, type: bug, type: improvement

#2096 [BUGFIX] Fix issue #2095
  amethyst_ui/src/drag.rs
Labels: status: done, status: waiting for merge
