Repository amethyst/amethyst, pull requests merged in 2020-06, with the labels that each got.

#2209 Fixes tiles example MapMovementSystem
  examples/tiles/main.rs
Labels: status: needs author changes

#2118 remove far plane from perspective projection
  amethyst_gltf/src/format/mod.rs
  amethyst_rendy/compiled/vertex/skybox.vert.spv
  amethyst_rendy/shaders/vertex/skybox.vert
  amethyst_rendy/src/bundle.rs
  amethyst_rendy/src/camera.rs
  amethyst_rendy/src/pass/base_3d.rs
  amethyst_rendy/src/pass/debug_lines.rs
  amethyst_rendy/src/pass/flat2d.rs
  amethyst_rendy/src/pass/skybox.rs
  amethyst_rendy/src/plugins.rs
  amethyst_rendy/src/submodules/gather.rs
  amethyst_rendy/src/visibility.rs
  amethyst_tiles/src/pass.rs
  amethyst_utils/src/auto_fov.rs
  amethyst_utils/src/ortho_camera.rs
  book/src/pong-tutorial/pong-tutorial-02.md
  book/src/pong-tutorial/pong-tutorial-03.md
  book/src/pong-tutorial/pong-tutorial-06.md
  book/src/sprites/orthographic_camera.md
  examples/asset_loading/main.rs
  examples/auto_fov/main.rs
  examples/debug_lines/main.rs
  examples/mouse_raycast/main.rs
  examples/renderable_custom/main.rs
  examples/sprites_ordered/main.rs
  examples/tiles/main.rs
Labels: status: done, team: rendering

#2315 amethyst_audio port to legion
  Cargo.toml
  amethyst_audio/src/bundle.rs
  amethyst_audio/src/components/audio_emitter.rs
  amethyst_audio/src/components/audio_listener.rs
  amethyst_audio/src/components/mod.rs
  amethyst_audio/src/output.rs
  amethyst_audio/src/source.rs
  amethyst_audio/src/systems/audio.rs
  amethyst_audio/src/systems/dj.rs
  amethyst_audio/src/systems/mod.rs
  amethyst_core/Cargo.toml
  src/lib.rs
Labels: pri: normal, status: ready
