Repository amethyst/amethyst, pull requests merged in 2021-01, with the labels that each got.

#2470 Add correct path to large files in examples
  .gitattributes
Labels: After 0.16

#2539 Added discord to the community section
  README.md
Labels: After 0.16

#2487 Allow more encodings for text assets and configs
  amethyst_assets/Cargo.toml
  amethyst_assets/src/source/dir.rs
  amethyst_assets/tests/assets/encodings/UTF16-BE-BOM
  amethyst_assets/tests/assets/encodings/UTF16-LE-BOM
  amethyst_assets/tests/assets/encodings/UTF8-BOM
  amethyst_config/Cargo.toml
  amethyst_config/src/lib.rs
  amethyst_config/tests/UTF16-BE-BOM.ron
  amethyst_config/tests/UTF16-LE-BOM.ron
  amethyst_config/tests/UTF8-BOM.ron
  amethyst_config/tests/config.ron
  docs/CHANGELOG.md
Labels: After 0.16

#2575 replace crates-io patch with git versioning
  Cargo.toml
  amethyst_assets/Cargo.toml
Labels: Legion

#2574 upgrade ron to 0.6.4
  Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_assets/src/prefab/assets.rs
  amethyst_assets/tests/prefab_test.rs
  amethyst_config/Cargo.toml
  amethyst_config/src/lib.rs
  amethyst_core/Cargo.toml
  amethyst_input/src/bundle.rs
  amethyst_input/src/sdl_events_system.rs
  amethyst_rendy/Cargo.toml
  amethyst_ui/Cargo.toml
  examples/prefab_atelier/main.rs
Labels: type: breaking

#2577 fix release-drafter config
  .github/release-drafter.yml
Labels: skip-changelog, type: maintenance

#2578 fix release-drafter version-resolver
  .github/release-drafter.yml
Labels: skip-changelog, type: maintenance

#2549 Port `amethyst_animation` to Legion
  .rusty-hook.toml
  Cargo.toml
  amethyst_animation/Cargo.toml
  amethyst_animation/src/bundle.rs
  amethyst_animation/src/lib.rs
  amethyst_animation/src/material.rs
  amethyst_animation/src/prefab.rs
  amethyst_animation/src/resources.rs
  amethyst_animation/src/skinning/resources.rs
  amethyst_animation/src/skinning/systems.rs
  amethyst_animation/src/sprite.rs
  amethyst_animation/src/systems/control.rs
  amethyst_animation/src/systems/mod.rs
  amethyst_animation/src/systems/sampling.rs
  amethyst_animation/src/transform.rs
  amethyst_animation/src/ui_transform.rs
  amethyst_animation/src/util.rs
  amethyst_assets/src/formats.rs
  amethyst_assets/src/lib.rs
  amethyst_audio/src/components/audio_emitter.rs
  amethyst_audio/src/output.rs
  amethyst_audio/src/sink.rs
  amethyst_derive/src/prefab_data.rs
  amethyst_input/src/bindings.rs
  amethyst_input/src/input_handler.rs
  amethyst_input/src/util.rs
  amethyst_network/src/simulation/transport/laminar.rs
  amethyst_network/src/simulation/transport/tcp.rs
  amethyst_network/src/simulation/transport/udp.rs
  amethyst_rendy/src/bundle.rs
  amethyst_rendy/src/formats/texture.rs
  amethyst_rendy/src/pass/skybox.rs
  amethyst_rendy/src/shape.rs
  amethyst_rendy/src/sprite_visibility.rs
  amethyst_rendy/src/submodules/environment.rs
  amethyst_rendy/src/submodules/material.rs
  amethyst_rendy/src/util.rs
  amethyst_rendy/src/visibility.rs
  amethyst_tiles/src/pass.rs
  amethyst_ui/src/button/builder.rs
  amethyst_ui/src/drag.rs
  amethyst_ui/src/font/default.rs
  amethyst_ui/src/glyphs.rs
  amethyst_ui/src/layout.rs
  amethyst_ui/src/pass.rs
  amethyst_utils/src/ortho_camera.rs
  build.rs
  examples/asset_custom/main.rs
  examples/custom_render_pass/custom_pass.rs
  examples/locale/main.rs
  examples/prefab/test.prefab
  examples/sprite_animation/assets/anims/bat.ron
  examples/sprite_animation/assets/sprites/bat.ron
  examples/sprite_animation/main.rs
  examples/sprite_camera_follow/main.rs
  examples/tiles/systems/draw_selection.rs
  rustfmt.toml
  src/state.rs
Labels: Legion, type: breaking, type: feature, type: improvement

#2582 fix debug_lines, debug_lines_ortho, sprite_animation examples
  Cargo.toml
  examples/debug_lines/main.rs
  examples/debug_lines_ortho/main.rs
  examples/sprite_animation/main.rs
Labels: Legion, type: improvement, type: maintenance

#2581 fix tiles example assets
  examples/tiles/assets/texture/Circle_Spritesheet.ron
  examples/tiles/assets/texture/cp437_20x20.ron
Labels: type: bug

#2584 Fix `mouse_raycast` and `animation` examples
  Cargo.toml
  amethyst_animation/src/sprite.rs
  amethyst_animation/src/util.rs
  amethyst_assets/src/loader.rs
  amethyst_ui/src/button/builder.rs
  amethyst_ui/src/format.rs
  amethyst_ui/src/glyphs.rs
  amethyst_ui/src/label.rs
  amethyst_ui/src/layout.rs
  amethyst_ui/src/pass.rs
  amethyst_ui/src/text.rs
  amethyst_ui/src/transform.rs
  examples/animation/main.rs
  examples/mouse_raycast/assets/texture/cp437_20x20.ron
  examples/mouse_raycast/main.rs
  examples/pong_tutorial_05/pong.rs
Labels: Legion, type: improvement, type: maintenance

#2525 Autoselect gfx (only works on nightly)
  .github/workflows/ci.yml
  .rusty-hook.toml
  Cargo.toml
  README.md
  amethyst_animation/Cargo.toml
  amethyst_animation/src/systems/control.rs
  amethyst_assets/src/asset.rs
  amethyst_assets/src/json.rs
  amethyst_assets/src/lib.rs
  amethyst_gltf/Cargo.toml
  amethyst_input/Cargo.toml
  amethyst_rendy/Cargo.toml
  amethyst_rendy/src/lib.rs
  amethyst_rendy/src/render_test_bundle.rs
  amethyst_rendy/src/sprite_visibility.rs
  amethyst_rendy/src/types.rs
  amethyst_test/Cargo.toml
  amethyst_tiles/Cargo.toml
  amethyst_ui/Cargo.toml
  book/src/appendices/c_feature_gates.md
  book/src/pong-tutorial.md
  book/src/prefabs/how_to_define_prefabs_adapter.md
  book/src/prefabs/how_to_define_prefabs_aggregate.md
  book/src/prefabs/how_to_define_prefabs_simple.md
  book/src/prefabs/prefabs_in_amethyst.md
  docs/CONTRIBUTING.md
  examples/README.md
  examples/debug_lines/main.rs
  script/coverage.sh
  script/publish.sh
Labels: Legion

#2588 Improve issue and pr templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-modification-request.md
  .github/ISSUE_TEMPLATE/maintenance-request.md
  .github/ISSUE_TEMPLATE/new-feature-request.md
  .github/pull_request_template.md
Labels: type: improvement, type: maintenance

#2585 Remove rusty hook and replace with optional cargo-husky hook
  Cargo.toml
  docs/CONTRIBUTING.md
  examples/events/main.rs
  examples/events_custom_state_event/main.rs
  script/pre-commit
Labels: team: infrastructure, type: maintenance

#2589 update atelier and remove long sleeps from tests
  .github/workflows/ci.yml
  amethyst_assets/tests/common.rs
  amethyst_core/src/timing.rs
Labels: type: bug, type: maintenance

#2540 Fix offset in TileMap positionning
  amethyst_tiles/src/map.rs
  docs/CHANGELOG.md
Labels: After 0.16

#2572 remove all defunct prefab code
  amethyst_animation/src/lib.rs
  amethyst_animation/src/prefab.rs
  amethyst_animation/src/resources.rs
  amethyst_animation/src/skinning/resources.rs
  amethyst_audio/src/components/mod.rs
  amethyst_audio/src/source.rs
  amethyst_controls/src/components.rs
  amethyst_derive/src/lib.rs
  amethyst_derive/src/prefab_data.rs
  amethyst_derive/tests/test.rs
  amethyst_gltf/src/lib.rs
  amethyst_rendy/src/camera.rs
  amethyst_rendy/src/formats/mesh.rs
  amethyst_rendy/src/formats/mod.rs
  amethyst_rendy/src/formats/mtl.rs
  amethyst_rendy/src/formats/texture.rs
  amethyst_rendy/src/light.rs
  amethyst_rendy/src/resources.rs
  amethyst_rendy/src/shape.rs
  amethyst_rendy/src/skinning.rs
  amethyst_rendy/src/sprite/mod.rs
  amethyst_rendy/src/sprite/prefab.rs
  amethyst_rendy/src/transparent.rs
  amethyst_tiles/src/lib.rs
  amethyst_tiles/src/prefab.rs
  amethyst_ui/src/bundle.rs
  amethyst_ui/src/drag.rs
  amethyst_ui/src/lib.rs
  amethyst_ui/src/prefab.rs
  amethyst_utils/src/auto_fov.rs
  amethyst_utils/src/lib.rs
  amethyst_utils/src/ortho_camera.rs
  amethyst_utils/src/removal.rs
  amethyst_utils/src/scene.rs
  amethyst_utils/src/tag.rs
  examples/prefab_basic/main.rs
  examples/prefab_custom/main.rs
  examples/prefab_multi/main.rs
  examples/rendy/main.rs
Labels: Legion, team: assets, type: maintenance

#2607 Legion Prefabs with Hot Reloading (based on #2567)
  Cargo.toml
  amethyst_assets/Cargo.toml
  amethyst_assets/src/asset.rs
  amethyst_assets/src/bundle.rs
  amethyst_assets/src/helper.rs
  amethyst_assets/src/loader.rs
  amethyst_assets/src/prefab/assets.rs
  amethyst_assets/src/prefab/component_registry.rs
  amethyst_assets/src/prefab/importers.rs
  amethyst_assets/src/prefab/mod.rs
  amethyst_assets/src/prefab/processor.rs
  amethyst_assets/src/prefab/system.rs
  amethyst_assets/src/processor.rs
  amethyst_assets/src/source/dir.rs
  amethyst_assets/src/storage.rs
  amethyst_assets/tests/assets/entity_with_dependencies.prefab
  amethyst_assets/tests/assets/spotlight.prefab
  amethyst_assets/tests/common/mod.rs
  amethyst_assets/tests/prefab_test.rs
  amethyst_audio/src/source.rs
  amethyst_core/Cargo.toml
  amethyst_core/src/lib.rs
  amethyst_core/src/logger.rs
  amethyst_locale/src/lib.rs
  amethyst_rendy/src/bundle.rs
  amethyst_rendy/src/sprite/mod.rs
  amethyst_rendy/src/system.rs
  amethyst_ui/src/format.rs
  amethyst_ui/src/glyphs.rs
  examples/pong_tutorial_06/audio.rs
  examples/pong_tutorial_06/main.rs
  examples/pong_tutorial_06/pong.rs
  examples/pong_tutorial_06/systems/bounce.rs
  examples/prefab/assets/prefab/example.ron
  examples/prefab/main.rs
  examples/prefab_atelier/.gitignore
  examples/prefab_atelier/Cargo.toml
  examples/prefab_atelier/assets/prefab/entity_with_a_transform.prefab
  examples/prefab_atelier/assets/prefab/example.prefab
  examples/prefab_atelier/assets/prefab/test.prefab
  examples/prefab_atelier/config/display.ron
  examples/prefab_atelier/main.rs
  src/lib.rs
Labels: Legion
